python3 train.py \
	--device=cuda \
	--seed=42 \
	--batch_size=64 \
	--input_size=300 \
	--hidden_size1=300 \
	--hidden_size2=300 \
	--epochs=1 \
	--lr=0.001 \
	--evaluation_epochs=1 \
	--optim=Adam \
	--loss_fun=CrossEntropyLoss \
	--if_load=False \
	--load_para= \
	--save_name=Test.pth \
	--if_save=False \
	--notes=首次实�