python3 train.py /
	--device=cuda /
	--seed=42 /
	--batch_size=64 /
	--input_size=300 /
	--hidden_size1=300 /
	--hidden_size2=300 /
	--epochs=100 /
	--lr=0.003 /
	--evaluation_epochs=1 /
	--optim=Adam /
	--loss_fun=CrossEntropyLoss /
	--if_load=False /
	--load_para= /
	--save_name=Test.pth /
	--if_save=False /
	--notes=长epoch实验,epoch=100,综合记录,alpha=0.4,gamma=0.91,lr=3e-3 /
	--debug=Fals